name: DEPLOY_API

on:
  push:
    branches: [ develop ]
    paths-ignore:
      - 'scripts/*'
      - 'README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HEROKU_USERNAME: ${{ secrets.HEROKU_USERNAME }}
      HEROKU_PASSWORD: ${{ secrets.HEROKU_PASSWORD }}

    steps:
    - uses: actions/checkout@v2

    - name: Login to heroku
      env:
        HEROKU_USERNAME: ${{ secrets.HEROKU_USERNAME }}
        HEROKU_PASSWORD: ${{ secrets.HEROKU_PASSWORD }}
      run: |
        echo "machine api.heroku.com" > ~/.netrc
        echo "  login $HEROKU_USERNAME" >> ~/.netrc
        echo "  password $HEROKU_PASSWORD" >> ~/.netrc
        echo "machine git.heroku.com" > ~/.netrc
        echo "  login $HEROKU_USERNAME" >> ~/.netrc
        echo "  password $HEROKU_PASSWORD" >> ~/.netrc
        
    - name: Set git variables
      run: |
        git config --global user.email "ntat.taco@gmail.com"
        git config --global user.name "noah tatko"

    - name: Publish to heroku git
      env:
        HEROKU_USERNAME: ${{ secrets.HEROKU_USERNAME }}
        HEROKU_PASSWORD: ${{ secrets.HEROKU_PASSWORD }}
        HEROKU_APP: geokit-api-np
      uses: akhileshns/heroku-deploy@v3.2.6 # This is the action
      with:
        heroku_api_key: $HEROKU_PASSWORD
        heroku_app_name: "geokit-api-np" #Must be unique in Heroku
        heroku_email: $HEROKU_USERNAME
